apiVersion: apps/v1
kind: Deployment
metadata:
  name: myappcheck
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: vedantpratap948/myapp:0.1
        ports:
        - containerPort: 80